name: Validate Renovate Configuration with renovate-config-validator
author: Shunsuke Suzuki
branding:
  icon: check
  color: yellow
description: |
  Validate Renovate Configuration with renovate-config-validator.
  npx is required.
inputs:
  node-version:
    description: |
      Node.js version. If the version is "none", the node installation is skipped.
      The version must be compatible with the version of Renovate.
    default: "24"
    required: false
  strict:
    description: Either true of false. If it's true, renovate-config-validator's --strict option is set
    default: "true"
    required: false
  validator_version:
    description: version of renovate-config-validator. By default, the latest version is used.
    required: false
  config_file_path:
    description: |
      Renovate Configuration file
      By default, the following files are validated.

      - .github/renovate.json
      - .github/renovate.json5
      - .gitlab/renovate.json
      - .gitlab/renovate.json5
      - .renovaterc.json
      - .renovaterc.json5
      - renovate.json
      - renovate.json5
      - .renovaterc

      You can specify multiple files by multiple lines.
    required: false
  npm_cache:
    description: |
      Enable npm cache to speed up the installation of renovate.
      If it's "true", the npm cache is enabled.
    default: "true"
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      if: inputs.node-version != 'none'
      with:
        node-version: ${{inputs.node-version}}
    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      if: inputs.npm_cache == 'true'
      with:
        path: ~/.npm
        key: renovate-npm-${{ runner.os }}
    - name: Validate Renovate Configuration with renovate-config-validator
      run: |
        set -eu
        pkg=renovate

        opts=""
        if [ "$STRICT" = "true" ]; then
          opts=--strict
        elif [ "$STRICT" != "false" ]; then
          echo '::error:: the input "strict" must be "true" or "false"'
          exit 1
        fi

        pkg="renovate@${VALIDATOR_VERSION:-latest}"

        if [ -n "$CONFIG_FILE_PATH" ]; then
          files=$(echo "$CONFIG_FILE_PATH" | tr '\n' ' ')
          echo "===> npx --yes --package \"$pkg\" -c \"renovate-config-validator $opts $files\"" >&2
          npx --yes --package "$pkg" -c "renovate-config-validator $opts $files"
          exit 0
        fi

        files=""
        for file in .github/renovate.json .github/renovate.json5 .gitlab/renovate.json .gitlab/renovate.json5 .renovaterc.json .renovaterc.json5 renovate.json renovate.json5 .renovaterc; do
          if [ -f "$file" ]; then
            files="$files $file"
          fi
        done
        if [ -z "$files" ]; then
          echo "===> No configuration file is found" >&2
          exit 0
        fi

        version=$(npx --yes --package "$pkg" -c 'renovate --version')
        echo "===> running renovate $version"
        echo "===> npx --yes --package \"$pkg\" -c \"renovate-config-validator $opts $files\"" >&2
        npx --yes --package "$pkg" -c "renovate-config-validator $opts $files"
      shell: bash
      env:
        VALIDATOR_VERSION: ${{inputs.validator_version}}
        CONFIG_FILE_PATH: ${{inputs.config_file_path}}
        STRICT: ${{inputs.strict}}
