---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**
  pull_request:
    branches: [main]
    paths:
    - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aquaproj/aqua-installer@v2.3.2
      with:
        aqua_version: v2.25.0
    - run: actionlint
