---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**
  pull_request:
    branches: [main]
    paths:
    - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aquaproj/aqua-installer@v3.0.0
      with:
        aqua_version: v2.27.2
    - run: actionlint
