---
name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./
      - name: Test a single file
        uses: ./
        with:
          config_file_path: renovate.json
      - name: Test multiple files
        uses: ./
        with:
          config_file_path: |
            renovate.json
            tests/renovate.json
      - id: files
        run: |
          set -euo pipefail
          files=$(git ls-files | grep renovate.json)
          # https://stackoverflow.com/a/74232400
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "files<<$EOF"
            echo "$files"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Pass files through output
        uses: ./
        with:
          config_file_path: ${{ steps.files.outputs.files }}
