---
name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  default:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
